name: Issue notifications

on:
  push:
    branches:
      - nadya73/issues-sync

jobs:
  mail:
    name: Send mail notification
    runs-on: trampoline
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.EMAIL_CONNECTION_URL}}
          subject: Github Actions test
          to: ytsaurus-github-issues@yandex-team.ru
          from: GithubYTsaurus


